name: ci

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  
  lint:
    name: "Markdown linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out the code
      - name: Lint Code Base
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: "**/*.md"
  test:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check contract sizes
        run: forge build --sizes

      - name: Run tests
        run: forge test -vvv

      - name: Run snapshot
        run: forge snapshot

      - name: Generate coverage report
        run: forge coverage --report lcov