name: CI

on:
  push:
    branches:
      - main
      - mvp
      - feat/pretty-ids
  pull_request:


jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test -vvv

      - name: Run snapshot
        run: forge snapshot