name: Linting

on:
  push:
    branches:
      - main
      - mvp
  pull_request:

jobs:
  linting:
    name: "Markdown linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out the code
      - name: Lint Code Base
        uses: avtodev/markdown-lint:v1
        with:
          args: "**/*.md"